steps:

# This step stops the database pod
- name: 'gcr.io/cloud-builders/kubectl'
  id: Stop Pod
  args:
    - 'scale'
    - 'deploy'
    - 'sql-server-stage'
    - '--replicas=0'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'  

# This step deploys to the Stage environment
- name: 'gcr.io/cloud-builders/gke-deploy'
  id: Deploy Stage
  args:
  - run
  - --filename=stage.yaml
  - --image=gcr.io/$PROJECT_ID/sql-server:$_SHORT_SHA
  - --output=/tmp/outputstage
  - --location=us-east1-b
  - --cluster=cluster-1  

# This step starts the database pod
- name: 'gcr.io/cloud-builders/kubectl'
  id: Scale Pod
  args:
    - 'scale'
    - 'deploy'
    - 'sql-server-dev'
    - '--replicas=1'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'    

# This step triggers the Prod Deployment
- name: 'gcr.io/cloud-builders/gcloud'
  id: Trigger Prod
  args:
  - builds
  - submit
  - --config
  - cloudbuild-prod.yaml
  - --substitutions
  - _SHORT_SHA=$_SHORT_SHA
  - .