
    
# This step stops the database pod
#- name: 'mcr.microsoft.com/mssql/server:2019-latest'
 # id: Stop Pod
  #args:
   # - 'scale'
    #- 'deploy'
    #- 'sql-server-dev'
    #- '--replicas=0'
  #env:
   # - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
   # - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'  


# This step deploys to the Dev environment
- name: 'mcr.microsoft.com/mssql/server:2019-latest'
  id: Deploy Dev
  args:
  - run
  - --filename=dev.yaml
  - --image=mcr.microsoft.com/mssql/server:2019-latest
  - --location=us-central1-c
  - --output=/tmp/outputdev
  - --location=us-central1-c
  - --cluster=cluster-1  

# This step starts the database pod
- name: 'mcr.microsoft.com/mssql/server:2019-latest'
  id: Scale Pod
  args:
    - 'scale'
    - 'deploy'
    - 'sql-server-dev'
    - '--replicas=1'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'    

# This step triggers the Stage deploy
- name: 'mcr.microsoft.com/mssql/server:2019-latest'
  id: Trigger Stage
  args:
  - builds
  - submit
  - --config
  - cloudbuild-stage.yaml
  - --substitutions
  - _SHORT_SHA=$_SHORT_SHA
  - .
