steps:
  # This step builds the container image.
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/sql-server:$SHORT_SHA'
    - '.'
  
  # This step pushes the image to Container Registry
  # The PROJECT_ID and SHORT_SHA variables are automatically
  # replaced by Cloud Build.
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
    - 'push'
    - 'gcr.io/$PROJECT_ID/sql-server:$SHORT_SHA'
  
  # This step stops the database pod
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Stop Pod
    args:
      - 'scale'
      - 'deploy'
      - 'sql-server-pre-dev'
      - '--replicas=0'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
  
  # This step deploys to the pre-dev environment
  - name: 'gcr.io/cloud-builders/gke-deploy'
    id: Deploy pre-dev
    args:
    - run
    - --filename=pre-dev.yaml
    - --image=gcr.io/$PROJECT_ID/sql-server:$SHORT_SHA
    - --location=us-central1-c
    - --output=/tmp/outputdev
    - --location=us-central1-c
    - --cluster=cluster-1  

  # This step scales up the database pod
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Scale Pod
    args:
      - 'scale'
      - 'deploy'
      - 'sql-server-pre-dev'
      - '--replicas=1'    
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
    
  # This step deploys to the dev environment 
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Trigger Dev
    args:
    - builds
    - submit
    - --config
    - cloudbuild-dev.yaml
    - --substitutions
    - _SHORT_SHA=$SHORT_SHA
    - .
  
