steps:

# This step stops the database pod
- name: 'gcr.io/cloud-builders/kubectl'
  id: Stop Pod
  args:
    - 'scale'
    - 'deploy'
    - 'sql-server-prod'
    - '--replicas=0'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'    


# This step deploys to the Prod environment
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=prod.yaml
  - --image=gcr.io/$PROJECT_ID/sql-server:$_SHORT_SHA
  - --output=/tmp/outputprod
  - --location=us-east1-b
  - --cluster=cluster-1  

# This step stops the database pod
- name: 'gcr.io/cloud-builders/kubectl'
  id: Scale Pod
  args:
    - 'scale'
    - 'deploy'
    - 'sql-server-prod'
    - '--replicas=1'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'  


