steps:

# This step deploys the dev application in Kubernetes
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=local.yaml
  - --image=mcr.microsoft.com/mssql/server:2017-latest
  - --location=us-east1-b
  - --output=/tmp/outputdev
  - --location=us-east1-b
  - --cluster=cluster-1  

# This step deploys the stage application in Kubernetes
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - builds
  - submit
  - --config
  - cloudbuild-dev.yaml
  - --substitutions
  - _SHORT_SHA=$SHORT_SHA
  - .
