apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sql-server-local
spec:
  serviceName: sql-server-local
  replicas: 1
  selector:
    matchLabels:
      app: sql-server-local
  template:
    metadata:
      labels:
        app: sql-server-local
    spec:
      containers:
      - name: sql-server
        image: gcr.io/constellation-275522/sql-server
        ports:
        - containerPort: 1433
          name: sql-server
        env:
        - name: MSSQL_PID
          value: "Express"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-server
              key: SA_PASSWORD
        resources:
          limits:
            cpu: ".5"
            memory: "500Mi"
          requests:
            cpu: ".5"
            memory: "500Mi"
        volumeMounts:
        - name: sql-server-local
          mountPath: /var/opt/mssql
        livenessProbe:
          tcpSocket:
            port: 1433
          initialDelaySeconds: 300
          periodSeconds: 30
        securityContext:
          privileged: true
  volumeClaimTemplates:
  - metadata:
      name: sql-server-local
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
---          
apiVersion: v1
kind: Service
metadata:
  name: sql-server-local
  labels:
    app: sql-server-local
spec:
  ports:
  - port: 1433
    name: sql-server-local
  selector:
    app: sql-server-local
  type: LoadBalancer
   