apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-server-pre-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-server-pre-dev
  template:
    metadata:
      labels:
        app: sql-server-pre-dev
    spec:
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
      - name: sql-server
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
          name: sql-server
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-server-dev
              key: SA_PASSWORD
        resources:
          limits:
            cpu: "2"
            memory: "4000Mi"
          requests:
            cpu: "2"
            memory: "4000Mi"
        volumeMounts:
        - name: sql-server-pre-dev
          mountPath: /var/opt/mssql
        livenessProbe:
          tcpSocket:
            port: 1433
          initialDelaySeconds: 300
          periodSeconds: 30
        securityContext:
          privileged: true
      volumes:
      - name: sql-server-pre-dev
        persistentVolumeClaim:
          claimName: sql-server-pre-dev
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-server-pre-dev
  labels:
    database: mssql-pre-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: vctr-citwdd-net-sc
---
apiVersion: v1
kind: Service
metadata:
  name: sql-server-pre-dev
  labels:
    app: sql-server-pre-dev
spec:
  ports:
  - port: 80
    targetPort: 1433
    name: sql-server-pre-dev
  selector:
    app: sql-server-pre-dev
  type: LoadBalancer
   
