apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-server-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-server-prod
  template:
    metadata:
      labels:
        app: sql-server-prod
    spec:
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
      - name: sql-server
        image: gcr.io/constellation-275522/sql-server
        ports:
        - containerPort: 1433
          name: sql-server
        env:
        - name: MSSQL_PID
          value: "Express"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: prod-sql-server
              key: SA_PASSWORD
        resources:
          limits:
            cpu: ".9"
            memory: "2000Mi"
          requests:
            cpu: ".9"
            memory: "2000Mi"
        volumeMounts:
        - name: sql-server-prod
          mountPath: /var/opt/mssql
        livenessProbe:
          tcpSocket:
            port: 1433
          initialDelaySeconds: 300
          periodSeconds: 30
        securityContext:
          privileged: true
      volumes:
      - name: sql-server-prod
        persistentVolumeClaim:
          claimName: sql-server-prod
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-server-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi            
---
apiVersion: v1
kind: Service
metadata:
  name: sql-server-prod
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: sql-server-prod
spec:
  ports:
  - port: 1433
    name: sql-server-prod
  selector:
    app: sql-server-prod
  type: LoadBalancer  
   