apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sql-server-prod
spec:
  serviceName: sql-server-prod
  replicas: 1
  selector:
    matchLabels:
      app: sql-server-prod
  template:
    metadata:
      labels:
        app: sql-server-prod
    spec:
      containers:
      - name: sql-server-prod
        image: gcr.io/constellation-275522/sql-server
        ports:
        - containerPort: 1433
          name: sql-server-prod
        env:
        - name: MSSQL_PID
          value: "Express"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-server-prod
              key: SA_PASSWORD
        resources:
          limits:
            cpu: "2"
            memory: "3000Mi"
          requests:
            cpu: "1"
            memory: "2000Mi"
        volumeMounts:
        - name: sql-server-prod
          mountPath: /var/opt/mssql
        livenessProbe:
          tcpSocket:
            port: 1433
          initialDelaySeconds: 3
          periodSeconds: 3
        securityContext:
          privileged: true
  volumeClaimTemplates:
  - metadata:
      name: sql-server-prod
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
---          
apiVersion: v1
kind: Service
metadata:
  name: sql-server-prod
  labels:
    app: sql-server-prod
spec:
  ports:
  - port: 1433
    name: sql-server-prod
  clusterIP: None
  selector:
    app: sql-server-prod    