apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-server-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-server-test
  template:
    metadata:
      labels:
        app: sql-server-test
    spec:
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
      - name: sql-server
        image: mcr.microsoft.com/mssql/server:2019-latest
        command: ["/opt/mssql/bin/sqlservr"]
        ports:
        - containerPort: 1433
          name: sql-server
        env:
        - name: MSSQL_PID
          value: "Express"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-sql-server
              key: SA_PASSWORD
        resources:
          limits:
            cpu: ".9"
            memory: "2000Mi"
          requests:
            cpu: ".9"
            memory: "2000Mi"
        volumeMounts:
        - name: sql-server-test
          mountPath: /var/opt/mssql
        livenessProbe:
          tcpSocket:
            port: 1433
          initialDelaySeconds: 300
          periodSeconds: 30
        securityContext:
          privileged: true
      volumes:
      - name: test-sql-pvc
        persistentVolumeClaim:
          claimName: test-sql-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: test-sql-pvc
 labels: 
   app: vima
   tier: backend
spec:
 accessModes:
 - ReadWriteOnce
 resources:
   requests:
     storage: 15Gi
 storageClassName: vsphere-csi-sc           
---
apiVersion: v1
kind: Service
metadata:
  name: sql-server-test
  annotations:
    cloud.google.com/load-balancer-type: "Internal"  
  labels:
    app: sql-server-test
spec:
  ports:
  - port: 1433
    name: sql-server-test
  selector:
    app: sql-server-test
  type: LoadBalancer  
   
   
